### ISSUE TITLE
Resolve production build/deploy

### ISSUE THREAD

**Issue by omegabytes** [lanebreach/frontend#19]
The build script should successfully build and deploy our front end. This will be run as part of a CI/CD pipeline on AWS. This blocks #6.

Context: 

running `yarn prod:start` results in the error:
```bash
ReferenceError: regeneratorRuntime is not defined
    at Object.<anonymous> (/Users/alex/Documents/Programming/lanebreach/frontend/public/dist/bundle-backend.js:1:2257)
    at r (/Users/alex/Documents/Programming/lanebreach/frontend/public/dist/bundle-backend.js:1:172)
    at Object.<anonymous> (/Users/alex/Documents/Programming/lanebreach/frontend/public/dist/bundle-backend.js:1:1109)
    at Object.<anonymous> (/Users/alex/Documents/Programming/lanebreach/frontend/public/dist/bundle-backend.js:1:1907)
    at r (/Users/alex/Documents/Programming/lanebreach/frontend/public/dist/bundle-backend.js:1:172)
    at /Users/alex/Documents/Programming/lanebreach/frontend/public/dist/bundle-backend.js:1:964
    at Object.<anonymous> (/Users/alex/Documents/Programming/lanebreach/frontend/public/dist/bundle-backend.js:1:973)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

what I _think_ is the issue is misconfigured `webpack/frontend.prod.js` and `webpack/backend.dev.js` files
I aligned the prod configs with the dev configs best I could, and got some new errors. I feel like this is moving in the right direction: 

```bash
ERROR in ./src/styles/grid.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .container {
|   max-width: 100%;
|   display: flex;
 @ ./src/components/pages/gallery/index.js 14:0-35
 @ ./src/routes/index.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi babel-polyfill ./src/index.js

ERROR in ./src/styles/navigation.css 2:0
Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
| /* Large */
> .navigation {
|   display: flex;
|   flex-flow: row wrap;
 @ ./src/components/navigation/index.js 12:0-38
 @ ./src/components/pages/gallery/index.js
 @ ./src/routes/index.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi babel-polyfill ./src/index.js
```

**Comment by timshoaf** [comment]
Do you want to utilize the native build solution for whichever cloud into which you choose to deploy, or might we do this externally with CircleCI?

**Comment by Mokosha** [comment]
My take is that to start with we should make a successful build trigger a deployment, so I would be in favor of plugging it into CircleCI (or Travis or whatever). I don't know the inner workings of each of those to know what's better though.

**Comment by omegabytes** [comment]
CircleCI is fine

**Comment by omegabytes** [comment]
We've been building and _sort of_ deploying successfully for a few cycles now. The current deploy issues are captured in #43 so I am closing this in favor of focusing on that. @Mokosha @timshoaf if this is still a valid issue please lmk so we can reopen and track. Thank you!
